# This is a basic workflow to help you get started with Actions

name: kubernetes

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Update kubeconfig
        shell: powershell
        run: k3d kubeconfig get mycluster | Set-Content -Path "$env:USERPROFILE\.kube\config"

      - name: Generate random pod name and apply
        shell: powershell
        run: |
          $id = -join ((65..90) + (97..122) | Get-Random -Count 6 | % {[char]$_})
          $yaml = @"
          apiVersion: v1
          kind: Pod
          metadata:
            name: mypod-$id
            namespace: default
            labels:
              name: mypod
          spec:
            containers:
            - name: mypod
              image: rancher/hello-world
          "@
          $yaml | kubectl apply -f - --validate=false

      - name: Check pods
        run: kubectl get pods -n <your-namespace>
