name: kubernetes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Update kubeconfig
        shell: powershell
        run: |
          k3d kubeconfig get mycluster | Set-Content -Path "$env:USERPROFILE\.kube\config"
          (Get-Content "$env:USERPROFILE\.kube\config") -replace 'host.docker.internal', '127.0.0.1' | Set-Content "$env:USERPROFILE\.kube\config"

      - name: Generate random pod name and apply
        shell: powershell
        run: |
          $id = -join ((97..122) | Get-Random -Count 6 | % {[char]$_})
          $yaml = @"
          apiVersion: v1
          kind: Pod
          metadata:
            name: mypod-$id
            namespace: default
            labels:
              name: mypod
          spec:
            containers:
            - name: mypod
              image: rancher/hello-world
          "@
          $yaml | kubectl apply -f - --validate=false

      - name: Check pods
        run: kubectl get pods -n default