name: My First Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Cleanup old container
        shell: powershell
        run: docker rm -f $(docker ps -aq); exit 0

      - name: Build Docker image
        run: docker build -t hello-world-nginx:v1 .

      - name: Run Docker container
        run: docker run -d -p 8080:80 hello-world-nginx:v1

      - name: Wait for container
        run: sleep 3

      - name: Test nginx response
        run: curl http://localhost:8080

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/florisdelahaye/hello-world-nginx
          tags: |
            type=ref,event=branch
            type=sha

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}